🐰 Keploy: 2025-06-27T22:31:28+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T22:31:28+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T22:31:33+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T22:31:33+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T22:33:55+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T22:33:55+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T22:37:08+05:30 	[34mINFO[0m	config file not found; proceeding with flags only
🐰 Keploy: 2025-06-27T22:37:08+05:30 	[34mINFO[0m	Using the last directory name as appName : onelinedaily-backend
🐰 Keploy: 2025-06-27T22:37:08+05:30 	[34mINFO[0m	Generated config file based on the flags that are used
🐰 Keploy: 2025-06-27T22:37:08+05:30 	[31mERROR[0m	failed to get service	{"command": "record", "error": "command not supported in non linux os. if you are on windows or mac, please use the dockerized version of your application"}
🐰 Keploy: 2025-06-27T22:37:08+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T22:37:08+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T23:32:27+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-27T23:32:27+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-27T18:04:08Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2025-06-27T18:04:08Z 	[33mWARN[0m	buildDelay is set to 30, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2025-06-27T18:04:08Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35
🐰 Keploy: 2025-06-27T18:04:08Z 	[34mINFO[0m	trying to inject network:keploy-network to the keploy container
🐰 Keploy: 2025-06-27T18:04:08Z 	[34mINFO[0m	Successfully injected network to the keploy container	{"Keploy container": "keploy-v2", "appNetwork": "keploy-network", "keploy container ip": "172.19.0.2"}
🐰 Keploy: 2025-06-27T18:04:11Z 	[34mINFO[0m	keploy initialized and probes added to the kernel.
🐰 Keploy: 2025-06-27T18:04:12Z 	[34mINFO[0m	starting UDP DNS server at addr :26789
🐰 Keploy: 2025-06-27T18:04:12Z 	[34mINFO[0m	starting TCP DNS server at addr :26789
🐰 Keploy: 2025-06-27T18:04:12Z 	[34mINFO[0m	Keploy has taken control of the DNS resolution mechanism, your application may misbehave if you have provided wrong domain name in your application code.
🐰 Keploy: 2025-06-27T18:04:12Z 	[34mINFO[0m	Proxy started at port:8081
🐰 Keploy: 2025-06-27T18:04:14Z 	[31mERROR[0m	Application stopped with the error	{"error": "exit status 125"}
🐰 Keploy: 2025-06-27T18:04:14Z 	[31mERROR[0m	error while running the app	{"error": "exit status 125"}
🐰 Keploy: 2025-06-27T18:04:14Z 	[31mERROR[0m	internal error occured while hooking into the application, hence stopping keploy
🐰 Keploy: 2025-06-27T18:04:14Z 	[34mINFO[0m	stopping Keploy	{"reason": "internal error occured while hooking into the application, hence stopping keploy"}
🐰 Keploy: 2025-06-27T18:04:14Z 	[34mINFO[0m	proxy stopped...
🐰 Keploy: 2025-06-27T18:04:17Z 	[34mINFO[0m	eBPF resources released successfully...
🐰 Keploy: 2025-06-27T18:04:17Z 	[31mERROR[0m	failed to record	{"error": "internal error occured while hooking into the application, hence stopping keploy"}
🐰 Keploy: 2025-06-27T18:04:17Z 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-27T18:04:17Z 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-27T23:34:18+05:30 	[34mINFO[0m	exiting the current process as the command is moved to docker
🐰 Keploy: 2025-06-28T08:07:54+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T08:07:54+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T02:37:56Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2025-06-28T02:37:56Z 	[33mWARN[0m	buildDelay is set to 30, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2025-06-28T02:37:56Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35
🐰 Keploy: 2025-06-28T02:37:56Z 	[34mINFO[0m	trying to inject network:keploy-network to the keploy container
🐰 Keploy: 2025-06-28T02:37:57Z 	[34mINFO[0m	Successfully injected network to the keploy container	{"Keploy container": "keploy-v2", "appNetwork": "keploy-network", "keploy container ip": "172.19.0.2"}
🐰 Keploy: 2025-06-28T02:38:03Z 	[34mINFO[0m	keploy initialized and probes added to the kernel.
🐰 Keploy: 2025-06-28T02:38:05Z 	[34mINFO[0m	starting TCP DNS server at addr :26789
🐰 Keploy: 2025-06-28T02:38:05Z 	[34mINFO[0m	starting UDP DNS server at addr :26789
🐰 Keploy: 2025-06-28T02:38:05Z 	[34mINFO[0m	Keploy has taken control of the DNS resolution mechanism, your application may misbehave if you have provided wrong domain name in your application code.
🐰 Keploy: 2025-06-28T02:38:05Z 	[34mINFO[0m	Proxy started at port:8081
🐰 Keploy: 2025-06-28T02:38:07Z 	[31mERROR[0m	Application stopped with the error	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T02:38:07Z 	[31mERROR[0m	error while running the app	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T02:38:07Z 	[31mERROR[0m	internal error occured while hooking into the application, hence stopping keploy
🐰 Keploy: 2025-06-28T02:38:07Z 	[34mINFO[0m	stopping Keploy	{"reason": "internal error occured while hooking into the application, hence stopping keploy"}
🐰 Keploy: 2025-06-28T02:38:07Z 	[34mINFO[0m	proxy stopped...
🐰 Keploy: 2025-06-28T02:38:11Z 	[34mINFO[0m	eBPF resources released successfully...
🐰 Keploy: 2025-06-28T02:38:11Z 	[31mERROR[0m	failed to record	{"error": "internal error occured while hooking into the application, hence stopping keploy"}
🐰 Keploy: 2025-06-28T02:38:11Z 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T02:38:11Z 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T08:08:12+05:30 	[34mINFO[0m	exiting the current process as the command is moved to docker
🐰 Keploy: 2025-06-28T08:10:32+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T08:10:32+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T02:40:33Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2025-06-28T02:40:33Z 	[33mWARN[0m	buildDelay is set to 30, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2025-06-28T02:40:33Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35
🐰 Keploy: 2025-06-28T02:40:33Z 	[34mINFO[0m	trying to inject network:keploy-network to the keploy container
🐰 Keploy: 2025-06-28T02:40:34Z 	[34mINFO[0m	Successfully injected network to the keploy container	{"Keploy container": "keploy-v2", "appNetwork": "keploy-network", "keploy container ip": "172.19.0.2"}
🐰 Keploy: 2025-06-28T02:40:36Z 	[34mINFO[0m	keploy initialized and probes added to the kernel.
🐰 Keploy: 2025-06-28T02:40:37Z 	[34mINFO[0m	starting UDP DNS server at addr :26789
🐰 Keploy: 2025-06-28T02:40:37Z 	[34mINFO[0m	starting TCP DNS server at addr :26789
🐰 Keploy: 2025-06-28T02:40:37Z 	[34mINFO[0m	Keploy has taken control of the DNS resolution mechanism, your application may misbehave if you have provided wrong domain name in your application code.
🐰 Keploy: 2025-06-28T02:40:37Z 	[34mINFO[0m	Proxy started at port:8081
🐰 Keploy: 2025-06-28T02:40:42Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "2", "Destination ConnectionID": "3", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.3:39508", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:40:42Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "0", "Destination ConnectionID": "1", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.3:39510", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:40:42Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:40:42Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:40:52Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "4", "Destination ConnectionID": "5", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.3:40266", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:40:52Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:40:52Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "6", "Destination ConnectionID": "7", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.3:40274", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:40:52Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:00Z 	[34mINFO[0m	🟠 Keploy has captured test cases for the user's application.	{"path": "/r-projects/onelinedaily/onelinedaily-backend/keploy-tests/keploy/test-set-0/tests", "testcase name": "test-1"}
🐰 Keploy: 2025-06-28T02:41:02Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "8", "Destination ConnectionID": "9", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.3:48716", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:02Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:02Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "10", "Destination ConnectionID": "11", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.3:48722", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:02Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:12Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "12", "Destination ConnectionID": "13", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.3:58398", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:12Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:12Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "14", "Destination ConnectionID": "15", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.3:58406", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:12Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:17Z 	[31mERROR[0m	failed to peek the request message in proxy	{"proxy port": 8081, "error": "read tcp 172.19.0.2:8081->172.19.0.3:32782: read: connection reset by peer"}
🐰 Keploy: 2025-06-28T02:41:17Z 	[31mERROR[0m	failed to handle the client connection	{"error": "read tcp 172.19.0.2:8081->172.19.0.3:32782: read: connection reset by peer"}
🐰 Keploy: 2025-06-28T02:41:22Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "18", "Destination ConnectionID": "19", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.3:32792", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:22Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:22Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "20", "Destination ConnectionID": "21", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.3:32802", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:22Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:41:30Z 	[34mINFO[0m	proxy stopped...
🐰 Keploy: 2025-06-28T02:41:32Z 	[34mINFO[0m	eBPF resources released successfully...
🐰 Keploy: 2025-06-28T02:41:32Z 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T02:41:32Z 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T08:11:34+05:30 	[34mINFO[0m	exiting the current process as the command is moved to docker
🐰 Keploy: 2025-06-28T08:15:53+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T08:15:53+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T02:45:53Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2025-06-28T02:45:53Z 	[33mWARN[0m	buildDelay is set to 30, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2025-06-28T02:45:53Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35
🐰 Keploy: 2025-06-28T02:45:53Z 	[34mINFO[0m	trying to inject network:keploy-network to the keploy container
🐰 Keploy: 2025-06-28T02:45:54Z 	[34mINFO[0m	Successfully injected network to the keploy container	{"Keploy container": "keploy-v2", "appNetwork": "keploy-network", "keploy container ip": "172.19.0.3"}
🐰 Keploy: 2025-06-28T02:45:55Z 	[34mINFO[0m	keploy initialized and probes added to the kernel.
🐰 Keploy: 2025-06-28T02:45:56Z 	[34mINFO[0m	starting UDP DNS server at addr :26789
🐰 Keploy: 2025-06-28T02:45:56Z 	[34mINFO[0m	starting TCP DNS server at addr :26789
🐰 Keploy: 2025-06-28T02:45:56Z 	[34mINFO[0m	Keploy has taken control of the DNS resolution mechanism, your application may misbehave if you have provided wrong domain name in your application code.
🐰 Keploy: 2025-06-28T02:45:56Z 	[34mINFO[0m	Proxy started at port:8081
🐰 Keploy: 2025-06-28T02:46:00Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "2", "Destination ConnectionID": "3", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:38146", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:46:00Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "0", "Destination ConnectionID": "1", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:38144", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:46:00Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:46:00Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:46:10Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "4", "Destination ConnectionID": "5", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:45872", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:46:10Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:46:10Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "6", "Destination ConnectionID": "7", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:45888", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:46:10Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:46:15Z 	[31mERROR[0m	failed to peek the request message in proxy	{"proxy port": 8081, "error": "read tcp 172.19.0.3:8081->172.19.0.4:48950: read: connection reset by peer"}
🐰 Keploy: 2025-06-28T02:46:15Z 	[31mERROR[0m	failed to handle the client connection	{"error": "read tcp 172.19.0.3:8081->172.19.0.4:48950: read: connection reset by peer"}
🐰 Keploy: 2025-06-28T02:46:20Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "10", "Destination ConnectionID": "11", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:48952", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:46:20Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:46:20Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "12", "Destination ConnectionID": "13", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:48966", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:46:20Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:46:27Z 	[34mINFO[0m	proxy stopped...
🐰 Keploy: 2025-06-28T02:46:30Z 	[34mINFO[0m	eBPF resources released successfully...
🐰 Keploy: 2025-06-28T02:46:30Z 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T02:46:30Z 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T08:16:31+05:30 	[34mINFO[0m	exiting the current process as the command is moved to docker
🐰 Keploy: 2025-06-28T08:22:05+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T08:22:05+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T02:52:06Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2025-06-28T02:52:06Z 	[33mWARN[0m	buildDelay is set to 30, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2025-06-28T02:52:06Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35
🐰 Keploy: 2025-06-28T02:52:06Z 	[34mINFO[0m	trying to inject network:keploy-network to the keploy container
🐰 Keploy: 2025-06-28T02:52:06Z 	[34mINFO[0m	Successfully injected network to the keploy container	{"Keploy container": "keploy-v2", "appNetwork": "keploy-network", "keploy container ip": "172.19.0.3"}
🐰 Keploy: 2025-06-28T02:52:07Z 	[34mINFO[0m	keploy initialized and probes added to the kernel.
🐰 Keploy: 2025-06-28T02:52:08Z 	[34mINFO[0m	starting UDP DNS server at addr :26789
🐰 Keploy: 2025-06-28T02:52:08Z 	[34mINFO[0m	starting TCP DNS server at addr :26789
🐰 Keploy: 2025-06-28T02:52:08Z 	[34mINFO[0m	Keploy has taken control of the DNS resolution mechanism, your application may misbehave if you have provided wrong domain name in your application code.
🐰 Keploy: 2025-06-28T02:52:08Z 	[34mINFO[0m	Proxy started at port:8081
🐰 Keploy: 2025-06-28T02:52:12Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "0", "Destination ConnectionID": "1", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:37320", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:12Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:12Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "2", "Destination ConnectionID": "3", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:37334", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:12Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:22Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "4", "Destination ConnectionID": "5", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:33522", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:22Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:22Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "6", "Destination ConnectionID": "7", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:33526", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:22Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:32Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "8", "Destination ConnectionID": "9", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:54092", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:32Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:32Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "10", "Destination ConnectionID": "11", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:54104", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:32Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:42Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "12", "Destination ConnectionID": "13", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:40452", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:42Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:42Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "14", "Destination ConnectionID": "15", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:40464", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:42Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:52Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "16", "Destination ConnectionID": "17", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:49146", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:52Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:52Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "18", "Destination ConnectionID": "19", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:49148", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:52:52Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:02Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "20", "Destination ConnectionID": "21", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:51368", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:02Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:02Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "22", "Destination ConnectionID": "23", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:51376", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:02Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:12Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "24", "Destination ConnectionID": "25", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:37398", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:12Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:12Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "26", "Destination ConnectionID": "27", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:37410", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:12Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:13Z 	[31mERROR[0m	failed to peek the request message in proxy	{"proxy port": 8081, "error": "read tcp 172.19.0.3:8081->172.19.0.4:37420: read: connection reset by peer"}
🐰 Keploy: 2025-06-28T02:53:13Z 	[31mERROR[0m	failed to handle the client connection	{"error": "read tcp 172.19.0.3:8081->172.19.0.4:37420: read: connection reset by peer"}
🐰 Keploy: 2025-06-28T02:53:22Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "30", "Destination ConnectionID": "31", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:48032", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:22Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:22Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "32", "Destination ConnectionID": "33", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:48042", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:22Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:53:25Z 	[34mINFO[0m	proxy stopped...
🐰 Keploy: 2025-06-28T02:53:29Z 	[34mINFO[0m	eBPF resources released successfully...
🐰 Keploy: 2025-06-28T02:53:29Z 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T02:53:29Z 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T08:23:30+05:30 	[34mINFO[0m	exiting the current process as the command is moved to docker
🐰 Keploy: 2025-06-28T08:25:28+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T08:25:28+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T02:55:29Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2025-06-28T02:55:29Z 	[33mWARN[0m	buildDelay is set to 30, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2025-06-28T02:55:29Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35
🐰 Keploy: 2025-06-28T02:55:29Z 	[34mINFO[0m	trying to inject network:keploy-network to the keploy container
🐰 Keploy: 2025-06-28T02:55:29Z 	[34mINFO[0m	Successfully injected network to the keploy container	{"Keploy container": "keploy-v2", "appNetwork": "keploy-network", "keploy container ip": "172.19.0.3"}
🐰 Keploy: 2025-06-28T02:55:31Z 	[34mINFO[0m	keploy initialized and probes added to the kernel.
🐰 Keploy: 2025-06-28T02:55:31Z 	[34mINFO[0m	starting UDP DNS server at addr :26789
🐰 Keploy: 2025-06-28T02:55:31Z 	[34mINFO[0m	starting TCP DNS server at addr :26789
🐰 Keploy: 2025-06-28T02:55:31Z 	[34mINFO[0m	Keploy has taken control of the DNS resolution mechanism, your application may misbehave if you have provided wrong domain name in your application code.
🐰 Keploy: 2025-06-28T02:55:31Z 	[34mINFO[0m	Proxy started at port:8081
🐰 Keploy: 2025-06-28T02:55:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "0", "Destination ConnectionID": "1", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53694", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:55:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:55:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "2", "Destination ConnectionID": "3", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53692", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:55:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:55:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "4", "Destination ConnectionID": "5", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:55660", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:55:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:55:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "6", "Destination ConnectionID": "7", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:55672", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:55:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:55:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "8", "Destination ConnectionID": "9", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:60402", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:55:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:55:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "10", "Destination ConnectionID": "11", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:60410", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:55:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "12", "Destination ConnectionID": "13", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:60734", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "14", "Destination ConnectionID": "15", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:60736", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "16", "Destination ConnectionID": "17", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:56766", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "18", "Destination ConnectionID": "19", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:56772", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "20", "Destination ConnectionID": "21", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53298", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "22", "Destination ConnectionID": "23", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53314", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "24", "Destination ConnectionID": "25", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:33612", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "26", "Destination ConnectionID": "27", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:33616", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "28", "Destination ConnectionID": "29", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:57650", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "30", "Destination ConnectionID": "31", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:57662", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "32", "Destination ConnectionID": "33", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:33606", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "34", "Destination ConnectionID": "35", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:33620", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:56:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "36", "Destination ConnectionID": "37", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53574", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "38", "Destination ConnectionID": "39", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53588", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "40", "Destination ConnectionID": "41", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:39358", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "42", "Destination ConnectionID": "43", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:39374", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "44", "Destination ConnectionID": "45", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:58044", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "46", "Destination ConnectionID": "47", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:58048", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "48", "Destination ConnectionID": "49", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:39640", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "50", "Destination ConnectionID": "51", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:39654", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "52", "Destination ConnectionID": "53", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:43938", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "54", "Destination ConnectionID": "55", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:43946", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "56", "Destination ConnectionID": "57", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:33840", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "58", "Destination ConnectionID": "59", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:33842", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:57:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "60", "Destination ConnectionID": "61", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:40802", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "62", "Destination ConnectionID": "63", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:40810", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "64", "Destination ConnectionID": "65", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:44502", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "66", "Destination ConnectionID": "67", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:44506", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "68", "Destination ConnectionID": "69", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53200", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "70", "Destination ConnectionID": "71", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53206", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "72", "Destination ConnectionID": "73", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:36020", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "74", "Destination ConnectionID": "75", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:36032", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "76", "Destination ConnectionID": "79", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:37840", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "77", "Destination ConnectionID": "78", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:37842", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "82", "Destination ConnectionID": "83", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:44194", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "80", "Destination ConnectionID": "81", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:44190", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:58:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "84", "Destination ConnectionID": "85", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:52860", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "86", "Destination ConnectionID": "87", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:52862", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "88", "Destination ConnectionID": "89", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53942", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "90", "Destination ConnectionID": "91", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53926", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:24Z 	[31mERROR[0m	failed to peek the request message in proxy	{"proxy port": 8081, "error": "read tcp 172.19.0.3:8081->172.19.0.4:53716: read: connection reset by peer"}
🐰 Keploy: 2025-06-28T02:59:24Z 	[31mERROR[0m	failed to handle the client connection	{"error": "read tcp 172.19.0.3:8081->172.19.0.4:53716: read: connection reset by peer"}
🐰 Keploy: 2025-06-28T02:59:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "94", "Destination ConnectionID": "95", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53724", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "96", "Destination ConnectionID": "97", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53732", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:37Z 	[34mINFO[0m	proxy stopped...
🐰 Keploy: 2025-06-28T02:59:40Z 	[34mINFO[0m	eBPF resources released successfully...
🐰 Keploy: 2025-06-28T02:59:40Z 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T02:59:40Z 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T08:29:41+05:30 	[34mINFO[0m	exiting the current process as the command is moved to docker
🐰 Keploy: 2025-06-28T08:29:49+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T08:29:49+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T02:59:49Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2025-06-28T02:59:49Z 	[33mWARN[0m	buildDelay is set to 30, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2025-06-28T02:59:49Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35
🐰 Keploy: 2025-06-28T02:59:49Z 	[34mINFO[0m	trying to inject network:keploy-network to the keploy container
🐰 Keploy: 2025-06-28T02:59:49Z 	[34mINFO[0m	Successfully injected network to the keploy container	{"Keploy container": "keploy-v2", "appNetwork": "keploy-network", "keploy container ip": "172.19.0.3"}
🐰 Keploy: 2025-06-28T02:59:51Z 	[34mINFO[0m	keploy initialized and probes added to the kernel.
🐰 Keploy: 2025-06-28T02:59:52Z 	[34mINFO[0m	starting UDP DNS server at addr :26789
🐰 Keploy: 2025-06-28T02:59:52Z 	[34mINFO[0m	starting TCP DNS server at addr :26789
🐰 Keploy: 2025-06-28T02:59:52Z 	[34mINFO[0m	Keploy has taken control of the DNS resolution mechanism, your application may misbehave if you have provided wrong domain name in your application code.
🐰 Keploy: 2025-06-28T02:59:52Z 	[34mINFO[0m	Proxy started at port:8081
🐰 Keploy: 2025-06-28T02:59:57Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "2", "Destination ConnectionID": "3", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:38560", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:57Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:57Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "0", "Destination ConnectionID": "1", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:38562", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T02:59:57Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:04Z 	[34mINFO[0m	🟠 Keploy has captured test cases for the user's application.	{"path": "/r-projects/onelinedaily/onelinedaily-backend/keploy-tests/keploy/test-set-1/tests", "testcase name": "test-1"}
🐰 Keploy: 2025-06-28T03:00:07Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "4", "Destination ConnectionID": "5", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:57260", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:07Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:07Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "6", "Destination ConnectionID": "7", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:57276", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:07Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:17Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "8", "Destination ConnectionID": "9", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:38322", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:17Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:17Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "10", "Destination ConnectionID": "11", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:38326", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:17Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:21Z 	[31mERROR[0m	failed to peek the request message in proxy	{"proxy port": 8081, "error": "read tcp 172.19.0.3:8081->172.19.0.4:38336: read: connection reset by peer"}
🐰 Keploy: 2025-06-28T03:00:21Z 	[31mERROR[0m	failed to handle the client connection	{"error": "read tcp 172.19.0.3:8081->172.19.0.4:38336: read: connection reset by peer"}
🐰 Keploy: 2025-06-28T03:00:27Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "14", "Destination ConnectionID": "15", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:50710", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:27Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:27Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "16", "Destination ConnectionID": "17", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:50726", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:27Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:00:34Z 	[34mINFO[0m	proxy stopped...
🐰 Keploy: 2025-06-28T03:00:37Z 	[34mINFO[0m	eBPF resources released successfully...
🐰 Keploy: 2025-06-28T03:00:37Z 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T03:00:37Z 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T08:30:38+05:30 	[34mINFO[0m	exiting the current process as the command is moved to docker
🐰 Keploy: 2025-06-28T08:44:36+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T08:44:36+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T03:14:37Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2025-06-28T03:14:37Z 	[33mWARN[0m	buildDelay is set to 30, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2025-06-28T03:14:37Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35
🐰 Keploy: 2025-06-28T03:14:37Z 	[34mINFO[0m	trying to inject network:keploy-network to the keploy container
🐰 Keploy: 2025-06-28T03:14:38Z 	[34mINFO[0m	Successfully injected network to the keploy container	{"Keploy container": "keploy-v2", "appNetwork": "keploy-network", "keploy container ip": "172.19.0.3"}
🐰 Keploy: 2025-06-28T03:14:40Z 	[34mINFO[0m	keploy initialized and probes added to the kernel.
🐰 Keploy: 2025-06-28T03:14:40Z 	[34mINFO[0m	starting UDP DNS server at addr :26789
🐰 Keploy: 2025-06-28T03:14:40Z 	[34mINFO[0m	starting TCP DNS server at addr :26789
🐰 Keploy: 2025-06-28T03:14:40Z 	[34mINFO[0m	Keploy has taken control of the DNS resolution mechanism, your application may misbehave if you have provided wrong domain name in your application code.
🐰 Keploy: 2025-06-28T03:14:40Z 	[34mINFO[0m	Proxy started at port:8081
🐰 Keploy: 2025-06-28T03:14:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "2", "Destination ConnectionID": "3", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:52442", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:14:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:14:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "0", "Destination ConnectionID": "1", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:52440", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:14:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:14:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "4", "Destination ConnectionID": "5", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:42276", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:14:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:14:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "6", "Destination ConnectionID": "7", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:42284", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:14:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "8", "Destination ConnectionID": "9", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:37966", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "10", "Destination ConnectionID": "11", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:37974", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "12", "Destination ConnectionID": "13", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:45586", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "14", "Destination ConnectionID": "15", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:45590", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "16", "Destination ConnectionID": "17", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:47960", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "18", "Destination ConnectionID": "19", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:47970", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "20", "Destination ConnectionID": "21", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:36052", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "22", "Destination ConnectionID": "23", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:36064", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "24", "Destination ConnectionID": "25", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:55242", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "26", "Destination ConnectionID": "27", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:55250", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "28", "Destination ConnectionID": "29", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:46314", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "30", "Destination ConnectionID": "31", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:46328", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:15:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "32", "Destination ConnectionID": "33", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:42646", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "34", "Destination ConnectionID": "35", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:42662", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "36", "Destination ConnectionID": "37", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:52930", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "38", "Destination ConnectionID": "39", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:52946", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "40", "Destination ConnectionID": "41", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:59462", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "42", "Destination ConnectionID": "43", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:59474", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "44", "Destination ConnectionID": "45", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:36506", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "46", "Destination ConnectionID": "47", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:36516", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "48", "Destination ConnectionID": "49", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:52072", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "50", "Destination ConnectionID": "51", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:52074", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "52", "Destination ConnectionID": "53", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:55558", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "54", "Destination ConnectionID": "55", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:55574", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:16:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "56", "Destination ConnectionID": "57", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53120", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "58", "Destination ConnectionID": "59", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:53126", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "60", "Destination ConnectionID": "61", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:38756", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "62", "Destination ConnectionID": "63", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:38772", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "64", "Destination ConnectionID": "65", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:46734", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "66", "Destination ConnectionID": "67", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:46748", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "68", "Destination ConnectionID": "69", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:35460", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "70", "Destination ConnectionID": "71", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:35468", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "72", "Destination ConnectionID": "73", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:38858", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:46Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "74", "Destination ConnectionID": "75", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:38866", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:46Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "76", "Destination ConnectionID": "77", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:41086", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:56Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "78", "Destination ConnectionID": "79", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:41100", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:17:56Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "80", "Destination ConnectionID": "81", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:43022", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:06Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "82", "Destination ConnectionID": "83", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:43038", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:06Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "84", "Destination ConnectionID": "85", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:58512", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:16Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "86", "Destination ConnectionID": "87", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:58516", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:16Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "88", "Destination ConnectionID": "89", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:49974", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:26Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "90", "Destination ConnectionID": "91", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:49984", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:26Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:27Z 	[31mERROR[0m	failed to peek the request message in proxy	{"proxy port": 8081, "error": "read tcp 172.19.0.3:8081->172.19.0.4:49998: read: connection reset by peer"}
🐰 Keploy: 2025-06-28T03:18:27Z 	[31mERROR[0m	failed to handle the client connection	{"error": "read tcp 172.19.0.3:8081->172.19.0.4:49998: read: connection reset by peer"}
🐰 Keploy: 2025-06-28T03:18:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "94", "Destination ConnectionID": "95", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:54424", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:36Z 	[31mERROR[0m	failed to dial the conn to destination server	{"Client ConnectionID": "96", "Destination ConnectionID": "97", "Destination IP Address": "[127.0.0.1]:27017", "Client IP Address": "172.19.0.4:54430", "proxy port": 8081, "server address": "[127.0.0.1]:27017", "error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T03:18:36Z 	[31mERROR[0m	failed to handle the client connection	{"error": "dial tcp 127.0.0.1:27017: connect: connection refused"}
🐰 Keploy: 2025-06-28T08:48:40+05:30 	[31mERROR[0m	failed to start keploy in docker	{"error": "exit status 0xc000013a"}
🐰 Keploy: 2025-06-28T08:48:40+05:30 	[31mERROR[0m	failed to run the command in docker	{"error": "exit status 0xc000013a"}
🐰 Keploy: 2025-06-28T08:48:40+05:30 	[31mERROR[0m	failed to validate flags	{"error": "exit status 0xc000013a"}
🐰 Keploy: 2025-06-28T08:48:40+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T08:48:40+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:00:53+05:30 	[31mERROR[0m	failed to get service	{"command": "record", "error": "command not supported in non linux os. if you are on windows or mac, please use the dockerized version of your application"}
🐰 Keploy: 2025-06-28T09:00:53+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:00:53+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:01:57+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T09:01:57+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T03:31:58Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2025-06-28T03:31:58Z 	[33mWARN[0m	buildDelay is set to 30, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2025-06-28T03:31:58Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35
🐰 Keploy: 2025-06-28T03:31:58Z 	[34mINFO[0m	trying to inject network:keploy-network to the keploy container
🐰 Keploy: 2025-06-28T03:31:58Z 	[34mINFO[0m	Successfully injected network to the keploy container	{"Keploy container": "keploy-v2", "appNetwork": "keploy-network", "keploy container ip": "172.19.0.3"}
🐰 Keploy: 2025-06-28T03:32:00Z 	[34mINFO[0m	keploy initialized and probes added to the kernel.
🐰 Keploy: 2025-06-28T03:32:01Z 	[34mINFO[0m	starting UDP DNS server at addr :26789
🐰 Keploy: 2025-06-28T03:32:01Z 	[34mINFO[0m	starting TCP DNS server at addr :26789
🐰 Keploy: 2025-06-28T03:32:01Z 	[34mINFO[0m	Keploy has taken control of the DNS resolution mechanism, your application may misbehave if you have provided wrong domain name in your application code.
🐰 Keploy: 2025-06-28T03:32:01Z 	[34mINFO[0m	Proxy started at port:8081
🐰 Keploy: 2025-06-28T03:32:02Z 	[31mERROR[0m	Application stopped with the error	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T03:32:02Z 	[31mERROR[0m	error while running the app	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T03:32:02Z 	[31mERROR[0m	internal error occured while hooking into the application, hence stopping keploy
🐰 Keploy: 2025-06-28T03:32:02Z 	[34mINFO[0m	stopping Keploy	{"reason": "internal error occured while hooking into the application, hence stopping keploy"}
🐰 Keploy: 2025-06-28T03:32:02Z 	[34mINFO[0m	proxy stopped...
🐰 Keploy: 2025-06-28T03:32:05Z 	[34mINFO[0m	eBPF resources released successfully...
🐰 Keploy: 2025-06-28T03:32:05Z 	[31mERROR[0m	failed to record	{"error": "internal error occured while hooking into the application, hence stopping keploy"}
🐰 Keploy: 2025-06-28T03:32:05Z 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T03:32:05Z 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T09:02:06+05:30 	[34mINFO[0m	exiting the current process as the command is moved to docker
🐰 Keploy: 2025-06-28T09:17:42+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T09:17:42+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T03:47:43Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2025-06-28T03:47:43Z 	[33mWARN[0m	buildDelay is set to 30, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2025-06-28T03:47:43Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35
🐰 Keploy: 2025-06-28T03:47:43Z 	[34mINFO[0m	trying to inject network:keploy-network to the keploy container
🐰 Keploy: 2025-06-28T03:47:43Z 	[34mINFO[0m	Successfully injected network to the keploy container	{"Keploy container": "keploy-v2", "appNetwork": "keploy-network", "keploy container ip": "172.19.0.4"}
🐰 Keploy: 2025-06-28T03:47:45Z 	[34mINFO[0m	keploy initialized and probes added to the kernel.
🐰 Keploy: 2025-06-28T03:47:46Z 	[34mINFO[0m	starting UDP DNS server at addr :26789
🐰 Keploy: 2025-06-28T03:47:46Z 	[34mINFO[0m	starting TCP DNS server at addr :26789
🐰 Keploy: 2025-06-28T03:47:46Z 	[34mINFO[0m	Keploy has taken control of the DNS resolution mechanism, your application may misbehave if you have provided wrong domain name in your application code.
🐰 Keploy: 2025-06-28T03:47:46Z 	[34mINFO[0m	Proxy started at port:8081
🐰 Keploy: 2025-06-28T03:48:16Z 	[33mWARN[0m	timeout waiting for the container to stop	{"containerID": "myapp"}
🐰 Keploy: 2025-06-28T03:48:16Z 	[34mINFO[0m	proxy stopped...
🐰 Keploy: 2025-06-28T03:48:19Z 	[34mINFO[0m	eBPF resources released successfully...
🐰 Keploy: 2025-06-28T03:48:19Z 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T03:48:19Z 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T09:18:20+05:30 	[34mINFO[0m	exiting the current process as the command is moved to docker
🐰 Keploy: 2025-06-28T09:18:48+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.14"}
🐰 Keploy: 2025-06-28T09:18:49+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T03:48:49Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2025-06-28T03:48:49Z 	[33mWARN[0m	buildDelay is set to 30, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2025-06-28T03:48:49Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35
🐰 Keploy: 2025-06-28T03:48:49Z 	[34mINFO[0m	trying to inject network:keploy-network to the keploy container
🐰 Keploy: 2025-06-28T03:48:49Z 	[34mINFO[0m	Successfully injected network to the keploy container	{"Keploy container": "keploy-v2", "appNetwork": "keploy-network", "keploy container ip": "172.19.0.4"}
🐰 Keploy: 2025-06-28T03:48:51Z 	[34mINFO[0m	keploy initialized and probes added to the kernel.
🐰 Keploy: 2025-06-28T03:48:53Z 	[34mINFO[0m	starting UDP DNS server at addr :26789
🐰 Keploy: 2025-06-28T03:48:53Z 	[34mINFO[0m	starting TCP DNS server at addr :26789
🐰 Keploy: 2025-06-28T03:48:53Z 	[34mINFO[0m	Keploy has taken control of the DNS resolution mechanism, your application may misbehave if you have provided wrong domain name in your application code.
🐰 Keploy: 2025-06-28T03:48:53Z 	[34mINFO[0m	Proxy started at port:8081
🐰 Keploy: 2025-06-28T03:48:54Z 	[31mERROR[0m	Application stopped with the error	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T03:48:54Z 	[31mERROR[0m	error while running the app	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T03:48:54Z 	[31mERROR[0m	internal error occured while hooking into the application, hence stopping keploy
🐰 Keploy: 2025-06-28T03:48:54Z 	[34mINFO[0m	stopping Keploy	{"reason": "internal error occured while hooking into the application, hence stopping keploy"}
🐰 Keploy: 2025-06-28T03:48:54Z 	[34mINFO[0m	proxy stopped...
🐰 Keploy: 2025-06-28T03:48:57Z 	[34mINFO[0m	eBPF resources released successfully...
🐰 Keploy: 2025-06-28T03:48:57Z 	[31mERROR[0m	failed to record	{"error": "internal error occured while hooking into the application, hence stopping keploy"}
🐰 Keploy: 2025-06-28T03:48:57Z 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T03:48:57Z 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T09:18:58+05:30 	[34mINFO[0m	exiting the current process as the command is moved to docker
